INSERT INTO category (description) VALUES ('American');
INSERT INTO category (description) VALUES ('Italian');
INSERT INTO category (description) VALUES ('Mexican');
INSERT INTO category (description) VALUES ('Fast Food');
INSERT INTO measure_unit (description) VALUES ('Teaspoon');
INSERT INTO measure_unit (description) VALUES ('Tablespoon');
INSERT INTO measure_unit (description) VALUES ('Cup');
INSERT INTO measure_unit (description) VALUES ('Pinch');
INSERT INTO measure_unit (description) VALUES ('Ounce');
INSERT INTO measure_unit (description) VALUES ('Dash');
INSERT INTO measure_unit (description) VALUES ('Unit');
INSERT INTO measure_unit (description) VALUES ('Bag');